apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-ui
  namespace: observability
spec:
  replicas: 2
  selector:
    matchLabels:
      app: observability-ui
  template:
    metadata:
      labels:
        app: observability-ui
    spec:
      serviceAccountName: observability-sa
      containers:
      - name: streamlit
        image: PLACEHOLDER_OBSERVABILITYUI_IMAGE
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: observability-ui