apiVersion: v1
kind: Service
metadata:
  name: observability-ui
  namespace: observability
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
  selector:
    app: observability-ui