version: 0.2
phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform --version
  pre_build:
    commands:
      - terraform init -backend-config="bucket=${bucket}" -backend-config="region=${region}"
  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Terraform apply completed on $(date)"

      # Install kubectl
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.0/2024-12-20/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      
      # Configure kubectl
      - aws eks update-kubeconfig --name ${prefix_code}-eks-cluster --region ${region}
      
      # Update aws-auth ConfigMap
      - |
        cat << EOF | kubectl apply -f -
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: aws-auth
          namespace: kube-system
        data:
          mapRoles: |
            - rolearn: ${developer_role_arn}
              username: build
              groups:
                - system:masters
        EOF
        
      - echo "Triggering ArgoCD pipeline"
      - aws codepipeline start-pipeline-execution --name ${prefix_code}-pipeline-argocd-build