version: 0.2
phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform --version
  pre_build:
    commands:
      - terraform init -backend-config="bucket=${bucket}" -backend-config="region=${region}"
  build:
    commands:
      - terraform destroy -auto-approve
  post_build:
    commands:
      - echo "Terraform destroy completed on $(date)"